# 숫자야구게임
# 컴퓨터가 랜덤으로 1~9 사이의 임의의 숫자를 3개 생성
# 사용자로부터 1~9 사이의 중복없는 3자리 숫자를 입력받음
# 456 == 임의의 숫자를 3개와 비교 => 3개의 숫자를 위치까지 다 맞췄다면 3스트라이크
# 위치 상관없이 2개만 맞추면 볼
# q를 입력받기 전까지는 계속 반복
# 3스트라이크가 나온다면 반복문 중단

# 오라클 연동
# baseball_records 테이블 생성
# record_id 자동증가, 게임일자, 걸린시간

import random
import time
from datetime import datetime
import oracledb

def make_answer():
    '''1~9 중 중복없는 3자리 숫자 생성'''
    numbers = list(range(1,10))
    picked_numbers = []

    while len(picked_numbers) < 3:
        pick_number = random.choice(numbers)

        if pick_number not in picked_numbers:
            picked_numbers.append(pick_number)
    return picked_numbers

# 정답 리스트 생성
answer = make_answer()
#  시도 횟수
attempts = 0
# 프로그램 중단 여부 
is_quit = False


def get_strike_ball(answerm, guess):
    '''답변하고 응답하고 비교 후 strike, ball값 리턴'''
    input_arr = [int(x) for x in guess]
    # input_arr = []
    # for x in guess:
    #     input_arr.append(int(x))

    # input_arr = list[map(int, guess)]

    strike = 0
    ball = 0

    for i in range(3):
        if input_arr[i] == answerm[i]:
            strike += 1
        elif input_arr[i] in answerm:
            ball += 1

    return strike, ball

import time
start = time.time()

while True:
    input_number = input("중복없는 `1~9의 숫자를 3개 입력해주세요").strip()
    if "q" in input_number :
        print("게임을 종료합니다.")
        is_quit = True
        break
    if len(input_number) != 3 or not input_number.isdigit():
        print("숫자를 3개 입력해주세요.")
        continue

    attempts += 1
    strike, ball = get_strike_ball(answer, input_number)
    print(f"{strike}스트라이크 {ball}볼")

    if strike == 3:
        print("3스트라이크입니다. 게임 종료")

        end = time.time()
        et = end - start
        elapsed = format(et, ".3f")

        print(f"시도횟수 {attempts}회, 걸린시간 : {elapsed}초")

        with oracledb.connect(user="python_user", password = "54321", dsn="localhost/xe") as conn:
            with conn.cursor() as cursor:
                try:
                    sql = """create table baseball_records(
                    record_id number(10) generated by default as identity primary key, 
                    corr_strike number(10),
                    corr_ball number(10),
                    attempts number(10),
                    playtime number(10),
                    regdate varchar2(50)
                    )"""
                    cursor.execute(sql)
                except oracledb.DatabaseError as e:
                    (error_obj,) = e.args
                    if error_obj.code == 955:
                        print(error_obj.message)
                        pass
                    else: 
                        raise

                now = datetime.now()
                nowDateTime = now.strftime("%Y-%m-%d %H:%M:%S")
                
                sql = "insert into baseball_records(corr_strike, corr_ball, attempts , playtime, regdate) values(:1, :2, :3, :4, :5)"
                cursor.execute(sql, (strike, ball, attempts, elapsed , nowDateTime))
                conn.commit()
        break

