"""
영단어 퀴즈 프로그램

1) words.csv를 읽어서 words 테이블에 최초 1회 시딩
2) words 테이블에서 무작위로 문제를 출제 (4지선다)
3) 채점 후 결과(총 문제수, 맞춘 개수, 날짜)를 quiz_records 테이블에 저장
4) 원하면 이어서 다시 풀 수 있음
"""

import csv
import random
from datetime import datetime

import oracledb

CSV_PATH = "./words.csv"
NUM_PROBLEMS = 5
NUM_CHOICES = 4

conn = oracledb.connect(user="python_user", password="54321", dsn="localhost/xe")
cursor = conn.cursor()


def load_words_from_csv(path=CSV_PATH):
    '''csv 파일을 읽어서 (word, meaning) 튜플 리스트로 반환'''
    with open(path, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f)   # 첫 줄을 헤더로 자동 인식해서 건너뜀
        return [(row["word"], row["meaning"]) for row in reader]


def seed_words_if_empty():
    '''words 테이블이 비어 있으면 csv 파일 내용을 채워 넣음'''
    cursor.execute("select word, meaning from words")
    if cursor.fetchall():
        return   # 이미 데이터가 있으면 아무것도 안 함

    words = load_words_from_csv()
    sql = "insert into words (word, meaning) values (:1, :2)"
    cursor.executemany(sql, words)
    conn.commit()
    print(f"단어 {len(words)}개를 words 테이블에 등록했습니다.\n")


def build_options(correct_answer, distractor_pool, num_choices=NUM_CHOICES):
    '''정답 1개 + 오답 여러 개를 섞어서 보기 리스트로 반환'''
    distractors = random.sample(distractor_pool, num_choices - 1)
    options = distractors + [correct_answer]
    random.shuffle(options)
    return options


def ask_question(number, word, options):
    '''문제 하나를 출력하고, 유효한 답이 들어올 때까지 입력받아 선택한 보기를 반환'''
    print(f"Question {number}: '{word}'의 뜻은?")
    for i, option in enumerate(options, start=1):
        print(f"  {i}. {option}")

    while True:
        answer = input("답안 번호를 입력해주세요 (1~4): ").strip()
        if answer in ("1", "2", "3", "4"):
            return options[int(answer) - 1]
        print("1~4 사이의 숫자를 입력해주세요.")


def run_quiz(num_problems=NUM_PROBLEMS):
    '''퀴즈 한 판 진행. (정답 개수, 틀린 단어 목록)을 반환'''
    cursor.execute("select word, meaning from words")
    all_words = cursor.fetchall()

    if len(all_words) < num_problems + (NUM_CHOICES - 1):
        print("퀴즈를 내기엔 단어 수가 부족합니다.")
        return 0, []

    questions = random.sample(all_words, num_problems)
    # 문제로 뽑힌 단어는 오답 후보에서 제외
    distractor_pool = [meaning for word, meaning in all_words if (word, meaning) not in questions]

    correct_count = 0
    wrong_words = []

    print("-" * 50)
    for i, (word, meaning) in enumerate(questions, start=1):
        options = build_options(meaning, distractor_pool)
        selected = ask_question(i, word, options)

        if selected == meaning:
            print("정답입니다!\n")
            correct_count += 1
        else:
            print(f"오답입니다. 정답은 '{meaning}'입니다.\n")
            wrong_words.append((word, meaning))

    print("-" * 50)
    print(f"결과 : {correct_count} / {num_problems}")
    if wrong_words:
        print("틀린 단어:")
        for word, meaning in wrong_words:
            print(f"  - {word} : {meaning}")
    print()

    return correct_count, wrong_words


def save_quiz_result(total, correct):
    '''퀴즈 결과를 quiz_records 테이블에 저장 (퀴즈 한 판이 끝났을 때 딱 한 번만 호출)'''
    try:
        sql = """create table quiz_records(
        record_id number(10) generated by default as identity primary key,
        total number(10),
        correct number(10),
        regdate varchar2(20)
        )"""
        cursor.execute(sql)
    except oracledb.DatabaseError as e:
        (error_obj,) = e.args
        if error_obj.code != 955:   # 955: 이미 존재하는 테이블
            raise

    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    sql = "insert into quiz_records(total, correct, regdate) values(:1, :2, :3)"
    cursor.execute(sql, (total, correct, now))
    conn.commit()


def main():
    seed_words_if_empty()

    while True:
        correct, _ = run_quiz()
        save_quiz_result(NUM_PROBLEMS, correct)

        again = input("한 번 더 풀어보시겠어요? (y/n): ").strip().lower()
        if again != "y":
            print("퀴즈를 종료합니다.")
            break


if __name__ == "__main__":
    try:
        main()
    finally:
        cursor.close()
        conn.close()
