# === Todo 관리 ===
# 1. 추가 2.목록 3.완료처리 4.삭제 5.종료
#  선택 : 1
# 할일 내용을 입력하세요 : 내용입력...
#  등록되었습니다 보이게. 

#  === Todo 관리 ===
# 1. 추가 2.목록 3.완료처리 4.삭제 5.종료       다시 보이게
# 선택 : 2
# --------------------------------
# 1. [미완료] 강아지 목욕(2026-08-20 12:38:00) ~~ 목록나오게

# 선택 : 3
# 완료 처리할 일의 번호를 입력하세요.   ex) 1
# 완료 처리되었습니다. 보이게
# 4번 삭제또한 같은 매커니즘으로
# 5번 종료 선택하면 멈추게




# 데이터베이스 테이블 구조
# todo_id 자동증가 + pk
# title not null, is_done number(1) default 0, created_at 작성일자 sysdate
import oracledb

conn =  oracledb.connect(user="python_user", password = "54321", dsn="localhost/xe")
cursor = conn.cursor()
# 미리 cursor를 변수 설정해두었기 때문에 with coursor:  로 시작할 필요가 하나도 없다. 그냥 적으면 됨

# 테이블 생성
try:
    sql = """create table todo_list(
    todo_id number(10) generated by default as identity primary key, 
    title varchar2(50) not null, 
    is_done number(1) default 0, 
    created_at date default sysdate       
    )"""
    # sysdate 앞에 default 붙여줘야함!
    cursor.execute(sql)
except oracledb.DatabaseError as e:
    (error_obj, ) = e.args
    if error_obj.code == 955:
        print(error_obj.message)
        pass

# todo 추가 함수
def add_todo():
    # 할일 내용을 입력하세요 : 내용입력...
    #  등록되었습니다 보이게. 
    # 또한 db에 등록까지.
    input_todo = input("할 일을 입력해주세요.").strip()
    if not input_todo:
        print("아무것도 입력되지 않았습니다.")
        return 
    elif input_todo.isdigit():
        print("숫자만 입력되었습니다. 할 일을 입력해주세요")
        return 

    try:
        sql = """insert into todo_list(title, created_at)
        values (:1, sysdate)"""
        cursor.execute(sql, (input_todo,))
        conn.commit()
        if cursor.rowcount > 0:
            print("등록되었습니다.\n")
    except oracledb.DatabaseError as e:
        (error_obj, ) = e.args
        if error_obj.code == 1:          #중복키
            print("이미 존재하는 아이디입니다")
            conn.rollback()
        else:
            raise


def list_todos():
    '''select'''
    try:    
        cursor.execute("select * from todo_list order by todo_id")
        rows = cursor.fetchall()
        # fetchall()은 호출하는 순간 결과를 다 소진
        # 한번 호출하면 다음건 빈 리스트로 돌려줌. 즉 한번 호출하면 변수선언하는게 좋음

        # todo 내용이 없는 경우
        if not rows:
            print("등록된 할 일 목록은 없습니다.\n")
            return
        print("-"*50)

        for todo_id, title, is_done, created_at in rows:
            status = "미완료"
            if is_done == 1:
                status = "완료"
            print(f"{todo_id}. [{status}] {title} ({created_at})")

    except oracledb.DatabaseError as e:
        (error_obj, ) = e.args
        print(error_obj.message)
        conn.rollback()



def update_todo():
    '''완료 처리'''

    # 목록 먼저 보여주기
    list_todos()

    input_update_todo = input("완료 처리할 일의 번호를 입력하세요.")
    if not input_update_todo:
        print("아무것도 입력되지 않았습니다.")
        return
    elif not input_update_todo.isdigit():
        print("완료 처리할 일의 번호를 다시 입력해주세요. 숫자로 입력하세요.")
        return

    try:
        sql = "update todo_list set is_done =1 where todo_id = (:1)"
        cursor.execute(sql, (int(input_update_todo), ))

        if cursor.rowcount == 0:     # 조회된 행의 개수를 반환
            print("해당 번호의 할 일이 없습니다")
            conn.rollback()
        else:     
            conn.commit()
            print("완료 처리되었습니다.\n")
    except oracledb.DatabaseError as e:
        (error_obj, ) = e.args
        print(error_obj.message)
        conn.rollback()

    
def delete_todo():
    '''삭제처리'''

    list_todos()

    input_delete_todo = input("삭제 처리할 번호를 입력하세요.")
    if not input_delete_todo:
        print("아무것도 입력되지 않았습니다.")
        return
    elif not input_delete_todo.isdigit():
        print("완료 처리할 일의 번호를 다시 입력해주세요. 숫자로 입력하세요.")
        return

    try:
        sql = "delete from todo_list where todo_id = (:1)"
        cursor.execute(sql, (int(input_delete_todo), ))

        if cursor.rowcount == 0:     # 조회된 행의 개수를 반환
            print("삭제할 번호의 할 일이 없습니다")
            conn.rollback()
        else:     
            conn.commit()
            print("삭제되었습니다.\n")

    except oracledb.DatabaseError as e:
        (error_obj, ) = e.args
        print(error_obj.message)
        conn.rollback()

def menu():
    while True:
        print("=== Todo")
        print("1. 추가 2.목록 3.완료처리 4.삭제 5.종료")

        choice = input("선택 : ")

        if choice == "1":
            add_todo()
        elif choice == "2":
            list_todos()
        elif choice == "3":
            update_todo()
        elif choice == "4":
            delete_todo()
        elif choice == "5":
            print("종료합니다.")
            break
        else:
            print("번호를 확인해주세요")

# 파이썬에서 "이 파일이 직접 실행됐을 때만 이 코드를 돌려라"는 뜻
# finally 는 try 안에서 어떤 일이 일어나도 무조건 실행되는 블록이다.
# 여기서는 이 게임이 어캐 끝나든 DB연결은 무조건 정리하라는 의미. 

if __name__ == "__main__":
    try:
        menu()
    finally:
        cursor.close()
        conn.close()