import random
import oracledb
import time

sentences = [
    "The quick brown fox jumps over the lazy dog", 
    "Python is a powerful programming language", 
    "Practice makes perfect every single day", 
    "Oracle database stores data reliably", 
    "Typing speed imporves with daily practice"
]

# sentences 문장 중 임의의 문장을 출제 후 사용자가 타이핑하는 시간을 잰 후 저장
# 정확도 계산

# 걸린시간, 정확도율, 날짜


conn =  oracledb.connect(user="python_user", password = "54321", dsn="localhost/xe")
cursor = conn.cursor()

try:
    sql = """create table typing_records(
        id number(10) generated by default as identity primary key, 
        elapsed varchar2(20) not null, 
        accuracy varchar2(20) not null, 
        playdate date default sysdate
    )"""
    cursor.execute(sql)

except oracledb.DatabaseError as e:
    (error_obj, ) = e.args
    if error_obj.code != 955:
        raise


# 문장 보여주고 입력받기 + 시간체크
def type_sentence():
    picked_sentence = random.choice(sentences)
    print(picked_sentence)
    start = time.time()
    typed_sentence = input("주어진 문장을 따라치세요.")
    end = time.time()
    elasped = end - start

    correct_rate = check_accuracy(picked_sentence, typed_sentence)
    return correct_rate, elasped
  
# 정확도 체크
# zip(원본, 입력값)을 쓰면 길이가 달라도 에러가 안 나요. zip()은 두 문자열 중 짧은 쪽 길이만큼만 짝지어주고 자동으로 멈춰요. IndexError 걱정 없이 안전하게 순회할 수 있어요
def check_accuracy(question, answer):

    correct_chars = sum(1 for a, b in zip(question, answer) if a == b)
    accuracy = correct_chars / len(question) * 100
    accuracy = format(accuracy, ".1f")
    return accuracy

# 실행
def run_typing(count = 1):
    for i in range(count):
        correct_rate, elasped = type_sentence()
        save_typing_result(elasped, correct_rate)
       

# db에 결과 저장
def save_typing_result(play_time, correct):
    sql = """insert into typing_records(elapsed, accuracy) values(:1, :2)"""
    cursor.execute(sql, (play_time, correct))
    conn.commit()


if __name__ == "__main__":
    try:
        run_typing(count=1)
    finally:
        cursor.close()
        conn.close()